### ISSUE TITLE
Paper broken link.

### ISSUE THREAD

**Issue by drewhamiltonasdf** [mposa/DIRCON#2]
Heya,

Just wanted to point out the paper seems to be a broken link in the Readme.md. At least for me.

Thanks for the great repo/work.

**Comment by mposa** [comment]
Thanks for pointing this out. We do have a more updated implementation here https://github.com/DAIRLab/dairlib/blob/main/systems/trajectory_optimization/dircon/dircon.h
though it's not a minimal version, as it's embedded into other code from our lab.

**Comment by drewhamiltonasdf** [comment]
> Thanks for pointing this out. We do have a more updated implementation here https://github.com/DAIRLab/dairlib/blob/main/systems/trajectory_optimization/dircon/dircon.h though it's not a minimal version, as it's embedded into other code from our lab.

Well, glad I mentioned it then, looks like I was digging around in the wrong repo! 😄. Thanks 🙏
